apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  namespace: karpenter
spec:
  # Number of seconds expected to pass before a pod is evicted.
  # This is a grace period when draining pods on node disruption/deprovisioning.
  expireAfter: 2592000s # 30 days

  # Prevents Karpenter from ever evicting this podassociated with this NodeClaim
  # if no parameters are set, all pods can be evicted
  consolidateAfter: 30s

  # Karpenter will consolidate nodes when nodes are under-utilized and at same
  # cost
  consolidationPolicy:
    nodes: "When Underutilized"
    consolidateAfter: 30s
    expireAfter: 604800s
    terminationGracePeriod: 30s

  # The weight of the node pool selects which NodePool should be used when
  # multiple NodePools are available. Higher weights are preferred.
  weight: 100

  # Disrupt policy for graceful node disruption
  disruption:
    consolidateAfter: 30s
    expireAfter: 604800s
    budgets:
    - nodes: "10%"
    consolidationPolicy:
      nodes: "When Underutilized"
    expirationsExpireAfter: 604800s

  # Template contains the node class and other node settings
  template:
    spec:
      requirements:
      # Instance family - workload optimized for AI/ML
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand", "spot"]
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c5.xlarge
        - c5.2xlarge
        - c6a.xlarge
        - c6a.2xlarge
        - m5.xlarge
        - m5.2xlarge
        - m6a.xlarge
        - m6a.2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: ["c5", "c6a", "m5", "m6a"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["4"]

      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

  # Limits for the node pool
  limits:
    cpu: "1000"
    memory: 1000Gi

  # Disruption budget for node disruptions
  disruption:
    consolidationPolicy:
      nodes: "When Underutilized"
    expireAfter: 604800s # 7 days
    budgets:
    - nodes: "10%"
      duration: 5m
      schedule: "0 9 * * mon-fri"
      reasons:
      - "Drifted"

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  namespace: karpenter
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole"
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    karpenter.sh/discovery: "true"
  tags:
    karpenter.sh/discovery: "true"
    Environment: "production"
    ManagedBy: "karpenter"
  userData: |
    #!/bin/bash
    # Custom user data for node initialization
    echo "Initializing AI Agent node"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  monitoring:
    enabled: true
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      deleteOnTermination: true
      encrypted: true
